// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBK5BBGEzH3ij2VvLjEapb6cnTSzPaDz8',
    appId: '1:339644828417:web:edc8fb4c178228407a6900',
    messagingSenderId: '339644828417',
    projectId: 'steps-tracker-559c3',
    authDomain: 'steps-tracker-559c3.firebaseapp.com',
    storageBucket: 'steps-tracker-559c3.firebasestorage.app',
    measurementId: 'G-342KJLDKMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpGJqrzyHv__ukd8lHstf_VBuOjZ4ZHQ',
    appId: '1:339644828417:android:2d0d59d7a329721c7a6900',
    messagingSenderId: '339644828417',
    projectId: 'steps-tracker-559c3',
    storageBucket: 'steps-tracker-559c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZcPigMUVImuGPzdgxm2YsT0qTRwTSBVo',
    appId: '1:339644828417:ios:278a48eabfef49187a6900',
    messagingSenderId: '339644828417',
    projectId: 'steps-tracker-559c3',
    storageBucket: 'steps-tracker-559c3.firebasestorage.app',
    iosBundleId: 'com.steps.myapp',
  );

}